{{- if .Values.publicServices.enabled -}}
{{- range .Values.publicServices.items }}
{{- $target := index $.Values.services .service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "connectsphere.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  {{- if or $.Values.publicServices.annotations .annotations }}
  annotations:
    {{- with $.Values.publicServices.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  selector:
    {{- include "connectsphere.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .service }}
  ports:
    - name: http
      port: {{ .port | default 80 }}
      targetPort: {{ .targetPort | default $target.servicePort }}
{{- end }}
{{- end }}
