steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -f
      - services/api-gateway/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-api-gateway:login-hotfix
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -f
      - services/auth-service/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-auth-service:login-hotfix
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform=linux/amd64
      - -f
      - services/websocket-gateway/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-websocket-gateway:login-hotfix
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-api-gateway:login-hotfix
  - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-auth-service:login-hotfix
  - us-central1-docker.pkg.dev/$PROJECT_ID/wapi-repo/wapi-websocket-gateway:login-hotfix
