import { Contact, Deal, Task, User, Workspace } from "@/lib/models";
import { WabaService } from "../messaging/waba-service";
import mongoose from "mongoose";

/**
 * SIMPLE ACTION EXECUTOR
 * Executes non-graph automation actions for CRM triggers.
 */
export class SimpleActionExecutor {
  static async execute(rule: any, context: any) {
    console.log(`[SimpleActionExecutor] Executing rule: ${rule.name} for deal: ${context.metadata?.dealId}`);

    const actions = rule.actions || [];
    for (const action of actions) {
      try {
        await this.runAction(action, context);
      } catch (err: any) {
        console.error(`[SimpleActionExecutor] Action failed: ${action.type}`, err.message);
        if (!action.continueOnFailure) break;
      }
    }
  }

  private static async runAction(action: any, context: any) {
    const { workspaceId, contactId, metadata } = context;
    const { type, config = {} } = action;

    switch (type) {
      case 'send_template':
        if (!config.templateName) throw new Error("Template name is required");
        
        // Fetch contact phone
        const contact = await Contact.findById(contactId);
        if (!contact?.phone) throw new Error("Contact phone not found");

        await WabaService.sendTemplateMessage(
          workspaceId,
          contact.phone,
          config.templateName,
          config.languageCode || 'en_US',
          config.components || [],
          {
            contactId,
            metadata: { source: 'crm_automation', ruleId: context.ruleId }
          }
        );
        break;

      case 'send_message':
      case 'text_message':
        if (!config.text && !config.body) throw new Error("Message text is required");
        const msgContact = await Contact.findById(contactId);
        if (!msgContact?.phone) throw new Error("Contact phone not found");

        await WabaService.sendTextMessage(
          workspaceId,
          msgContact.phone,
          config.text || config.body,
          {
            contactId,
            metadata: { source: 'crm_automation', ruleId: context.ruleId }
          }
        );
        break;

      case 'send_interactive':
        if (!config.interactive) throw new Error("Interactive payload is required");
        const intContact = await Contact.findById(contactId);
        if (!intContact?.phone) throw new Error("Contact phone not found");

        await WabaService.sendInteractiveMessage(
          workspaceId,
          intContact.phone,
          config.interactive,
          {
            contactId,
            metadata: { source: 'crm_automation', ruleId: context.ruleId }
          }
        );
        break;

      case 'add_tag':
        if (!config.tag) throw new Error("Tag name is required");
        await Contact.findByIdAndUpdate(contactId, {
          $addToSet: { tags: config.tag }
        });
        break;

      case 'create_task':
        await Task.create({
          workspace: new mongoose.Types.ObjectId(workspaceId),
          title: config.title || `Follow up: ${metadata?.dealId || 'Deal'}`,
          description: config.description || "Auto-generated by CRM Automation",
          type: config.taskType || 'Follow-up',
          priority: config.priority || 'Medium',
          dueDate: new Date(Date.now() + (config.delayHours || 24) * 60 * 60 * 1000),
          relatedDeal: metadata?.dealId ? new mongoose.Types.ObjectId(metadata.dealId) : undefined,
          relatedContact: new mongoose.Types.ObjectId(contactId),
          assignee: config.assigneeId ? new mongoose.Types.ObjectId(config.assigneeId) : undefined
        });
        break;

      case 'assign_agent':
        if (!config.agentId) throw new Error("Agent ID is required");
        if (metadata?.dealId) {
          await Deal.findByIdAndUpdate(metadata.dealId, {
            assignedAgent: new mongoose.Types.ObjectId(config.agentId)
          });
        }
        break;

      default:
        console.warn(`[SimpleActionExecutor] Unknown action type: ${type}`);
    }
  }
}
